version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/brewcraft
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3600
      runas: root
